Repository team-gu/service, pull requests merged in 2021-07, with the labels that each got.

#13 GitHub의 변경점이 push에 따라 GitLab에 미러링되는 CI를 구성한다
  .github/workflows/mirror-to-gitlab.yml
Labels: DevOps, feature

#12 Delete `␍` eslint 에러를 해결한다
  FE/.eslintrc
Labels: bug

#16 framer 모듈을 설치한다
  FE/package.json
  FE/yarn.lock
Labels: FE, env

#17 FloatButton 컴포넌트를 구현하고 스토리를 추가한다
  FE/components/atoms/Icon/Icon.tsx
  FE/components/molecules/FloatButton/FloatButton.stories.js
  FE/components/molecules/FloatButton/FloatButton.tsx
  FE/components/molecules/FloatButton/index.ts
  FE/components/molecules/index.ts
Labels: FE, done, feature

#18 Storybook을 각 브랜치별로 push시점에 gh-pages로 배포되도록 처리한다
  .github/workflows/deploy-storybook-to-gh-pages.yml
  FE/.gitignore
  FE/package.json
Labels: DevOps, FE, done

#15 페이지 맨 하단에 붙는 footer 구성
  FE/components/organisms/Footer/Footer.tsx
  FE/components/organisms/Footer/index.ts
  FE/components/organisms/index.ts
  FE/pages/_app.tsx
  FE/pages/index.style.ts
Labels: FE, done, feature

#14 스크롤 이벤트에 반응하는 네브바 구성
  FE/components/organisms/Navbar/Navbar.tsx
  FE/hooks/useWindow.ts
Labels: FE, done, feature, 공통 컴포넌트

#19 OpenVidu 모듈 테스트
  FE/components/organisms/VideoChat/OpenViduVideoComponent.tsx
  FE/components/organisms/VideoChat/UserVideoComponent.tsx
  FE/components/organisms/VideoChat/VideoChat.stories.jsx
  FE/components/organisms/VideoChat/VideoChat.tsx
  FE/components/organisms/VideoChat/index.ts
  FE/components/organisms/index.ts
  FE/package.json
  FE/pages/rtc/index.tsx
  FE/yarn.lock
Labels: FE, feature, 커뮤니케이션

#22 Checkbox HOC 컴포넌트를 제작하고 스토리를 작성한다
  FE/components/molecules/Checkbox/Checkbox.stories.jsx
  FE/components/molecules/Checkbox/Checkbox.tsx
  FE/components/molecules/Checkbox/index.ts
  FE/components/molecules/index.ts
  FE/yarn.lock
Labels: FE, done, feature, 공통 컴포넌트

#25 next/image와 겹치는 Image 컴포넌트를 제거한다
  FE/components/atoms/Image/Image.stories.jsx
  FE/components/atoms/Image/Image.test.jsx
  FE/components/atoms/Image/Image.tsx
  FE/components/atoms/Image/index.ts
  FE/components/atoms/index.ts
Labels: FE, done, fix, 공통 컴포넌트

#24 Storybook에서 next/image로 절대경로에 접근할 수 있도록 설정한다
  FE/.storybook/preview.js
  FE/package.json
Labels: FE, done, fix

#27 eslint에서 발생하는 Cannot find module 'next/babel' 문제 해결
  FE/.eslintrc
Labels: FE, done, fix

#28 Title HOC 컴포넌트 및 스토리를 구현한다
  FE/components/molecules/Title/Title.stories.tsx
  FE/components/molecules/Title/Title.tsx
  FE/components/molecules/Title/index.ts
  FE/components/molecules/index.ts
Labels: FE, feature, 공통 컴포넌트

#30 필요없는 alias 설정을 수정합니다
  FE/.babelrc
Labels: FE, done, fix

#23 레이아웃을 따로 구성하고 네브바와 푸터의 스토리를 추가합니다
  FE/components/organisms/Footer/Footer.stories.tsx
  FE/components/organisms/Layout/Layout.stories.tsx
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/Layout/index.ts
  FE/components/organisms/Navbar/Navbar.stories.tsx
  FE/components/organisms/index.ts
  FE/pages/_app.tsx
Labels: FE, done, feature, 공통 컴포넌트

#21 화상채팅 세션 참가 전 설정 모달
  FE/components/atoms/Input/Input.tsx
  FE/components/molecules/Button/Button.tsx
  FE/components/organisms/VideoChat/index.ts
  FE/components/organisms/index.ts
  FE/components/webrtc/OpenViduVideoComponent.tsx
  FE/components/webrtc/UserVideoComponent.tsx
  FE/components/webrtc/VideoChat.stories.jsx
  FE/components/webrtc/VideoChat.tsx
  FE/components/webrtc/VideoRoomConfigModal.stories.jsx
  FE/components/webrtc/VideoRoomConfigModal.tsx
  FE/components/webrtc/index.ts
  FE/components/webrtc/types/device-type.ts
  FE/components/webrtc/types/layout-type.ts
  FE/components/webrtc/types/logger-type.ts
  FE/components/webrtc/util/DeviceUtil.ts
  FE/components/webrtc/util/LoggerUtil.ts
  FE/components/webrtc/util/Util.ts
  FE/package-lock.json
  FE/package.json
  FE/pages/rtc/index.tsx
Labels: FE, 커뮤니케이션

#32 framer를 사용하여 page transition시 애니메이션을 적용합니다
  FE/components/organisms/Layout/Layout.tsx
Labels: FE, done, feature, 공통 컴포넌트

#26 ProfileImage 컴포넌트 및 스토리를 구현한다
  FE/components/molecules/ProfileImage/ProfileImage.stories.tsx
  FE/components/molecules/ProfileImage/ProfileImage.tsx
  FE/components/molecules/ProfileImage/index.ts
  FE/components/molecules/index.ts
  FE/public/profile.svg
  FE/styles/styled.d.ts
  FE/styles/theme.ts
Labels: FE, done, feature, 공통 컴포넌트

#34 Storybook 빌드가 실패하는 원인을 찾아서 해결한다
  FE/components/webrtc/VideoChat.stories.jsx
  FE/components/webrtc/VideoChat.stories.tsx
  FE/components/webrtc/VideoRoomConfigModal.stories.jsx
  FE/components/webrtc/VideoRoomConfigModal.stories.tsx
Labels: FE, done, fix

#36 JWT 로그인 기능을 구현한다
  BE/teamgu/TeamguApplicationTests.java
  BE/teamgu/build.gradle
  BE/teamgu/src/main/java/com/teamgu/TeamguApplication.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/LoginReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/BaseResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/LoginResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/JwtAuthEntryPoint.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/JwtRequestFilter.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/JwtUserDetailsService.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/TeamguUserDetails.java
  BE/teamgu/src/main/java/com/teamgu/common/util/JwtTokenUtil.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/config/SpringFoxConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepository.java
  BE/teamgu/src/main/resources/application.yml
Labels: BE, 로그인

#33 Summary 컴포넌트 및 스토리를 구현한다
  FE/components/molecules/Summary/Summary.stories.tsx
  FE/components/molecules/Summary/Summary.tsx
  FE/components/molecules/Summary/index.ts
  FE/package.json
  FE/yarn.lock
Labels: FE, done, feature, 공통 컴포넌트

#37 ProfileContainer 컴포넌트 및 스토리를 구현한다
  FE/components/atoms/Text/Text.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.stories.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
  FE/components/molecules/ProfileContainer/index.ts
  FE/components/molecules/ProfileImage/ProfileImage.stories.tsx
  FE/components/molecules/ProfileImage/ProfileImage.tsx
  FE/components/molecules/index.ts
  FE/public/profile.png
  FE/public/profile.svg
Labels: FE, done, feature, 공통 컴포넌트

#39 fix: Build되지 않던 오류 수정
  BE/teamgu/build.gradle
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QBaseEntity.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QChat.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QChatRoom.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QCode.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QCodeDetail.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QConference.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QMapping.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QNotice.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QNoticeFile.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QProjectDetail.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QQuiz.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QQuizScore.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QSkill.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QStdClass.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QTeam.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUser.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserAward.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserChat.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserClass.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserConference.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserFile.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserFollow.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserProject.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QUserTeam.java
  BE/teamgu/src/main/generated/com/teamgu/database/entity/QWishTrack.java
Labels: BE, DevOps, bug

#38 화상채팅 툴바 구현
  FE/components/webrtc/OpenViduVideoComponent.tsx
  FE/components/webrtc/VideoChat.tsx
  FE/components/webrtc/VideoChatToolbar.stories.tsx
  FE/components/webrtc/VideoChatToolbar.tsx
  FE/components/webrtc/VideoRoomConfigModal.stories.tsx
  FE/components/webrtc/VideoRoomConfigModal.tsx
  FE/components/webrtc/index.ts
  FE/components/webrtc/util/DeviceUtil.ts
Labels: FE, feature, 커뮤니케이션

#40 ProfileContainer 노티피케이션 props 작동하도록 작업한다
  FE/components/molecules/ProfileContainer/ProfileContainer.stories.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
Labels: FE, done, feature, 커뮤니케이션

#44 로그인 기능을 수정하고 토큰 기간 만료시 토큰을 재생성 한다.
  BE/teamgu/build.gradle
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/DummyReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TokenReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TokenResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/JwtRequestFilter.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/JwtUserDetailsService.java
  BE/teamgu/src/main/java/com/teamgu/common/auth/TeamguUserDetails.java
  BE/teamgu/src/main/java/com/teamgu/common/util/JwtTokenUtil.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepository.java
  BE/teamgu/src/main/resources/application.yml
Labels: BE

#42 Tag 컴포넌트 및 스토리를 구현한다
  FE/components/atoms/Text/Text.tsx
  FE/components/molecules/Tag/Tag.stories.tsx
  FE/components/molecules/Tag/Tag.tsx
  FE/components/molecules/Tag/index.ts
  FE/components/molecules/index.ts
  FE/styles/styled.d.ts
  FE/styles/theme.ts
Labels: FE, done, feature, 공통 컴포넌트

#43 storybook 배포 파이프라인 내부 링크를 변경된 프로젝트 이름으로 수정한다
  .github/workflows/deploy-storybook-to-gh-pages.yml
Labels: DevOps, FE, done, hotfix

#47 ChatInput 컴포넌트 및 스토리를 구현한다
  FE/components/atoms/Input/Input.tsx
  FE/components/molecules/ChatInput/ChatInput.stories.tsx
  FE/components/molecules/ChatInput/ChatInput.tsx
  FE/components/molecules/ChatInput/index.ts
  FE/components/molecules/ProfileImage/ProfileImage.tsx
  FE/components/molecules/index.ts
  FE/styles/theme.ts
Labels: FE, done, feature, 커뮤니케이션

#50 ChatBubble 컴포넌트 및 스토리를 구현한다
  FE/components/atoms/Text/Text.tsx
  FE/components/molecules/ChatBubble/ChatBubble.stories.tsx
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatBubble/index.ts
  FE/components/molecules/index.ts
Labels: FE, done, feature, 커뮤니케이션

#45 화상채팅 레이아웃
  FE/components/webrtc/OpenViduVideoComponent.tsx
  FE/components/webrtc/UserVideoComponent.tsx
  FE/components/webrtc/VideoChat.tsx
  FE/components/webrtc/VideoChatLayout.stories.tsx
  FE/components/webrtc/VideoChatToolbar.tsx
  FE/components/webrtc/VideoRoomConfigModal.stories.tsx
  FE/package.json
  FE/yarn.lock
Labels: FE, feature, 커뮤니케이션

#51 메인페이지의 상단부 완성
  FE/components/organisms/Navbar/Navbar.tsx
  FE/pages/index.tsx
  FE/public/star1.png
  FE/public/star2.png
  FE/public/star3.png
  FE/public/star4.png
  FE/public/star5.png
  FE/public/star6.png
  FE/public/star7.png
  FE/public/star8.png
Labels: FE, done, 공통 컴포넌트

#54 화상채팅 시간 카운터 컴포넌트 구현
  FE/components/webrtc/FloatingCounter.stories.tsx
  FE/components/webrtc/FloatingCounter.tsx
  FE/components/webrtc/VideoChat.tsx
  FE/components/webrtc/VideoChatToolbar.tsx
  FE/components/webrtc/VideoRoomConfigModal.tsx
Labels: FE, feature, 커뮤니케이션

#52 공지사항 목록 및 세부사항 조회 완성
  BE/teamgu/build.gradle
  BE/teamgu/src/main/java/com/teamgu/api/controller/NoticeController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeFileResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeListResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/NoticeService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/NoticeServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/NoticeRepository.java
  BE/teamgu/src/main/java/com/teamgu/mapper/NoticeDetailMapper.java
  BE/teamgu/src/main/java/com/teamgu/mapper/NoticeFileMapper.java
  BE/teamgu/src/main/java/com/teamgu/mapper/NoticeListMapper.java
  BE/teamgu/src/main/resources/application.yml
Labels: BE, 공지사항

#56 SecurityConfig 파일 복원 및 매핑 오류 수정
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Notice.java
  BE/teamgu/src/main/java/com/teamgu/mapper/NoticeDetailMapper.java
  BE/teamgu/src/main/java/com/teamgu/mapper/NoticeFileMapper.java
Labels: BE, fix, 공지사항

#53 ChatRoom 컴포넌트 및 스토리를 구현한다
  FE/components/atoms/Input/Input.tsx
  FE/components/atoms/Text/Text.tsx
  FE/components/molecules/Button/Button.tsx
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatInput/ChatInput.tsx
  FE/components/organisms/ChatRoom/ChatRoom.stories.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoom/index.ts
  FE/components/organisms/index.ts
  FE/package.json
  FE/yarn.lock
Labels: FE, done, feature, 커뮤니케이션

#57 마이페이지 등록, 수정 기능을 수정한다.
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/AwardReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/PasswordReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ProjectReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/LoginResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TokenResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/config/QuerydslJpaQueryConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/CodeDetail.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Mapping.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/ProjectDetail.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserAward.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/WishTrack.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/CodeDetailPK.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/ProjectDetailPK.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/WishTrackPK.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AwardRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AwardRepositorySuport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/CodeDetailRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/CodeDetailRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectDetailRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectDetailRepositorySuport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectRepositorySuport.java
Labels: BE, 유저 편의 기능

#58 공지사항 삭제 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/NoticeController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/BasicResponse.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/CommonResponse.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ErrorResponse.java
  BE/teamgu/src/main/java/com/teamgu/api/service/NoticeService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/NoticeServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Notice.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/NoticeFileRepository.java
Labels: BE, feature, 공지사항

#62 role 자료형 변경과 로그인 서버에러 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/DummyReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
Labels: BE, fix, 로그인

#63 fix: localhost:3000 CORS 조치
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
Labels: BE, fix

#65 next.config.js에 ts.ignoreBuildErrors 옵션을 추가한다
  FE/next.config.js
Labels: FE, done, fix

#66 화상채팅 세션 내 채팅 화면
  FE/components/molecules/FloatButton/FloatButton.stories.tsx
  FE/components/molecules/FloatButton/FloatButton.tsx
  FE/components/molecules/FloatButton/index.ts
  FE/components/molecules/FloatingButton/FloatingButton.stories.tsx
  FE/components/molecules/FloatingButton/FloatingButton.tsx
  FE/components/molecules/FloatingButton/index.ts
  FE/components/molecules/index.ts
  FE/components/webrtc/FloatingChatButton.stories.tsx
  FE/components/webrtc/FloatingChatButton.tsx
  FE/components/webrtc/FloatingCounter.tsx
  FE/components/webrtc/SidebarChat.stories.tsx
  FE/components/webrtc/SidebarChat.tsx
  FE/components/webrtc/VideoChat.tsx
  FE/components/webrtc/VideoChatLayout.stories.tsx
  FE/components/webrtc/VideoChatToolbar.tsx
  FE/components/webrtc/VideoRoomConfigModal.tsx
  FE/components/webrtc/index.ts
Labels: FE, feature, 커뮤니케이션

#67 DB 무한 루프 에러와 Entity를 수정했습니다
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Chat.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/ChatRoom.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/CodeDetail.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Conference.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/StdClass.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Team.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserAward.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserChat.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserClass.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserConference.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserFile.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserProject.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserTeam.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/CodeDetailPK.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/UserChatPK.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/UserConferencePK.java
Labels: BE, DB, hotfix

#70 로그인과 로그아웃을 구현했습니다
  FE/components/molecules/Button/Button.tsx
  FE/components/organisms/LoginComponent/LoginComponent.tsx
  FE/components/organisms/Navbar/Navbar.tsx
  FE/context/serverContext.ts
  FE/pages/humanpool/index.tsx
  FE/pages/index.tsx
  FE/pages/main/index.tsx
  FE/pages/userdetail/index.tsx
  FE/public/favicon.ico
  FE/public/logo.png
  FE/public/logo.svg
  FE/repository/baseRepository.ts
  FE/store/authSlice.ts
Labels: FE, 공통 컴포넌트, 로그인

#68 채팅 관련 퍼블리싱된 것 각 페이지에 적용한다
  FE/components/atoms/Icon/Icon.tsx
  FE/components/molecules/ChatInput/ChatInput.tsx
  FE/components/molecules/FloatingButton/FloatingButton.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.stories.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
  FE/components/organisms/ChatList/ChatList.stories.tsx
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatList/index.ts
  FE/components/organisms/ChatRoom/ChatRoom.stories.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoute/ChatRoute.stories.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/ChatRoute/index.ts
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/index.ts
  FE/store/index.ts
  FE/store/uiSlice.ts
  FE/utils/constants.ts
Labels: FE, done, 커뮤니케이션

#71 README.md를 작성한다
  README.md
Labels: docs
