Repository team-gu/service, pull requests merged in 2021-08, with the labels that each got.

#81 fix : 이름, 사진, 트랙, 반 추가
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserClassResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoAwardResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoProjectResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserInfoAward.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserInfoProject.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/SkillPK.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/WishTrackPK.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AwardRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AwardRepositorySuport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectRepositorySuport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserQueryRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, fix, 로그인, 유저 편의 기능

#86 fix : 인력풀 관련 Entity 수정
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserProjectDetail.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/UserProjectDetailPK.java
Labels: BE, fix

#85 공통컴포넌트 중 textarea를 구현합니다.
  FE/components/atoms/Textarea/Textarea.stories.tsx
  FE/components/atoms/Textarea/Textarea.tsx
  FE/components/atoms/Textarea/index.ts
  FE/components/atoms/index.ts
Labels: FE, done, 공통 컴포넌트

#84 공통 컴포넌트 SimpleSelect
  FE/components/molecules/SimpleSelect/SimpleSelect.stories.tsx
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/SimpleSelect/index.ts
  FE/components/molecules/index.ts
  FE/package.json
  FE/yarn.lock
Labels: FE, feature, 공통 컴포넌트

#87 공통 컴포넌트 UserSelectAutoComplete
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.stories.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/molecules/UserSelectAutoComplete/index.ts
  FE/repository/baseRepository.ts
Labels: FE, feature, 공통 컴포넌트

#88 공통 컴포넌트 SkillSelectAutoComplete
  FE/components/molecules/SkillSelectAutoComplete/SkillSelectAutoComplete.stories.tsx
  FE/components/molecules/SkillSelectAutoComplete/SkillSelectAutoComplete.tsx
  FE/components/molecules/SkillSelectAutoComplete/index.ts
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/repository/baseRepository.ts
Labels: FE, feature, 공통 컴포넌트

#89 feat: User Info Project / Award CRUD
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoAwardResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoProjectResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AwardRepositorySuport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectRepositorySuport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserInfoAwardRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserInfoProjectRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, DB, feature, 로그인

#90 팀 페이지 뷰
  FE/components/atoms/Input/Input.tsx
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/index.ts
  FE/components/organisms/TeamStatus/TeamStatus.stories.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatus/index.ts
  FE/components/organisms/TeamStatusCard/TeamStatusCard.stories.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/components/organisms/TeamStatusCard/index.ts
  FE/components/organisms/index.ts
  FE/pages/team/index.tsx
  FE/repository/baseRepository.ts
  FE/styles/styled.d.ts
  FE/styles/theme.ts
  FE/utils/constants.ts
Labels: FE, feature, 팀관리

#91 채팅 전송/수신 및 DB 저장과 채팅 관련 부가 기능을 추가했습니다
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/StompChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/UserChatRoomDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserRoomCheckDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatMessageResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatRoomResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/config/WebSocketConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Chat.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/ChatRoom.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/QuizPK.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserChatRoom.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/UserChatRoomPK.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRoomRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: BE, DB, 커뮤니케이션

#92 로그인시 받아오는 데이터 수정
  FE/store/authSlice.ts
Labels: FE, done, 로그인

#82 Stomp 연결 로직 및 채팅관련 엔드포인트를 컴포넌트에 연결한다
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatBubbleSelect/ChatBubbleSelect.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/Layout/Layout.tsx
  FE/hooks/useSockStomp.ts
  FE/package.json
  FE/repository/chatRepository.ts
  FE/types/chat-type.d.ts
  FE/utils/constants.ts
  FE/yarn.lock
Labels: FE, feature, 커뮤니케이션

#94 feat : Code detail에 대한 엔드 포인트 생성
  BE/teamgu/src/main/java/com/teamgu/api/controller/CodeController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/CodeDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/CodeService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/CodeServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/CodeDetailRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/CodeDetailRepositoryImpl.java
  BE/teamgu/src/main/java/com/teamgu/mapper/CodeDetailMapper.java
Labels: BE, feature

#93 fix : User Detail Info 수정 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Mapping.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/MappingRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/MappingRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserSkillRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserSkillRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/WishTrackRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/WishTrackRepositorySupport.java
Labels: BE, fix

#95 Input에 ref를 사용할 때 value를 사용할 수 없는 현상 해결
  FE/components/atoms/Input/Input.tsx
  FE/components/atoms/Textarea/Textarea.tsx
Labels: FE, fix

#97 팀 페이지 팀 생성, 수정 모달
  FE/components/atoms/Textarea/Textarea.tsx
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/SkillSelectAutoComplete/SkillSelectAutoComplete.stories.tsx
  FE/components/molecules/SkillSelectAutoComplete/SkillSelectAutoComplete.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.stories.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/organisms/Modal/AlertModal/AlertModal.stories.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.stories.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamManageModal/index.ts
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.stories.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/components/organisms/index.ts
  FE/repository/baseRepository.ts
  FE/utils/constants.ts
  FE/utils/type.ts
Labels: FE, feature, 팀관리

#101 textarea를 기존으로 돌립니다
  FE/components/atoms/Textarea/Textarea.tsx
Labels: FE, done, fix

#99 팀 페이지 정렬
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/repository/baseRepository.ts
Labels: FE, feature, 팀관리

#103 팀 페이지 카드, 모달 스타일 수정
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
Labels: FE, fix, 팀관리

#102 fix: select문 introduce와 position 순서를 변경한다.
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, fix, 유저 편의 기능

#100 스킬에 맞는 color와 background 속성을 주고 마이페이지를 완성합니다
  FE/components/molecules/SkillSelectAutoComplete/SkillSelectAutoComplete.tsx
  FE/components/molecules/Tag/Tag.tsx
  FE/components/organisms/ChatRoom/ChatRoom.stories.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/AwardModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/index.ts
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/components/organisms/UserDetail/MyDetail/index.ts
  FE/components/organisms/UserDetail/UserDetail.tsx
  FE/repository/baseRepository.ts
  FE/repository/projects.ts
  FE/store/authSlice.ts
  FE/utils/type.ts
Labels: FE, done

#106 관리자 페이지 사이드바 메뉴
  FE/components/molecules/SimpleSelect/SimpleSelect.stories.tsx
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/organisms/AdminMenuSidebarLeft/AdminMenuSidebarLeft.stories.tsx
  FE/components/organisms/AdminMenuSidebarLeft/AdminMenuSidebarLeft.tsx
  FE/components/organisms/AdminMenuSidebarLeft/index.ts
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/utils/type.ts
Labels: FE, feature, 관리자 편의 기능

#108 SSL 인증을 추가한다
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserRoomInviteReqDto.java
  BE/teamgu/src/main/resources/application.yml
Labels: BE

#104 feat : 인력풀 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserPoolController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, feature, 인력풀

#111 서버 https 설정이 된 부분을 클라이언트 url에 반영한다
  FE/context/serverContext.ts
  FE/hooks/useSockStomp.ts
Labels: FE, done, hotfix

#109 관리자 페이지 프로젝트 조회 카드 컴포넌트
  FE/components/molecules/ProjectCard/ProjectCard.stories.tsx
  FE/components/molecules/ProjectCard/ProjectCard.tsx
  FE/components/molecules/ProjectCard/index.ts
  FE/components/organisms/LookupLayout/LookupLayout.tsx
  FE/styles/styled.d.ts
  FE/styles/theme.ts
  FE/utils/type.ts
Labels: FE, feature, 관리자 편의 기능

#113 비로그인 상태에서 로그인이 필요한 페이지로 이동시 리다이렉트
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.stories.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.stories.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/repository/baseRepository.ts
  FE/utils/type.ts
Labels: FE, fix, 로그인

#112 fix : 유저풀 sql문 수정
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, bug, fix, 인력풀

#114 마이페이지에서 발생하는 사소한 버그들을 수정합니다.
  FE/components/organisms/Navbar/Navbar.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/AwardModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/repository/userprofile.ts
  FE/store/authSlice.ts
  FE/store/index.ts
Labels: FE, feature

#116 팀 생성/수정 모달 로직 수정
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/repository/baseRepository.ts
  FE/utils/type.ts
Labels: FE, 팀관리, fix

#117 로그인 수행시 에러가 나면 아래 에러 메시지를 출력합니다
  FE/components/organisms/LoginComponent/LoginComponent.tsx
  FE/store/authSlice.ts
Labels: FE, 로그인, fix, done

#115 fix : Dto 내에 사용안하는 swagger example 제거
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/NoticeReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/CodeDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeFileResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/NoticeListResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolResDto.java
Labels: BE, 인력풀, fix

#119 fix : 인력풀 반환 데이터 변경
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
Labels: BE, 인력풀, fix

#121 fix : 인력풀 반환 데이터형 변경
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserPoolController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, fix

#122 feat: Team CRUD 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/SkillResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamListResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamMemberInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Team.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/TeamSkill.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/TeamSkillPK.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/MappingRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserSkillRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/WishTrackRepositorySupport.java
Labels: BE, 팀관리, DB, feature

#118 채팅방에 가면 뒤로가기 버튼이 활성화 된다
  FE/components/organisms/ChatRoute/ChatRoute.tsx
Labels: FE, 커뮤니케이션, feature, done

#124 fix: User Detail Info Response 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
Labels: BE, 로그인, 유저 편의 기능, fix

#125 fix : 인력풀에서 팀에 속하지 않은 인원만 보이게 한다
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolReqDto.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, fix

#120 팀 생성/수정 모달에서 삭제 기능
  FE/components/organisms/TeamManageModal/TeamManageModal.stories.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.stories.tsx
  FE/repository/baseRepository.ts
  FE/repository/teamRepository.ts
Labels: FE, 팀관리, feature

#110 인력풀 페이지를 제작한다
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatus/index.ts
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/components/organisms/UserStatusCard/index.ts
  FE/components/organisms/index.ts
  FE/components/webrtc/VideoChat.tsx
  FE/pages/humanpool/index.tsx
  FE/pages/rtc/[id]/index.tsx
  FE/repository/filterRepository.ts
  FE/utils/constants.ts
  FE/utils/snippet.ts
Labels: FE, 인력풀, feature

#126 채팅창에서의 유저 검색 자동 완성 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/SearchController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserChatSearchReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInviteTeamReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserRoomInviteReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatRoomResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserChatSearchResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ProjectDetailService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ProjectDetailServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectDetailRepository.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectDetailRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: BE

#127 filterContent undefined 처리 등 놓친 부분을 해결한다
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
Labels: FE, hotfix, done

#128 상단 수정부 수정 버튼 클릭시 바로 반영되도록 구성합니다
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/store/authSlice.ts
  FE/store/index.ts
Labels: FE, feature

#129 WebRTC 닉네임 설정
  FE/components/webrtc/SidebarChat.tsx
  FE/components/webrtc/VideoChat.tsx
Labels: FE, 커뮤니케이션, fix

#130 포지션 선택 부분 수정
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
Labels: FE, fix

#131 WebRTC 세션 설정 모달에서 닉네임 보여지게 수정
  FE/components/webrtc/VideoRoomConfigModal.tsx
Labels: FE, 커뮤니케이션, hotfix

#134 Feature/user pool
  BE/teamgu/src/main/java/com/teamgu/api/controller/CodeController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/CodeDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/CodeService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/CodeServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/CodeDetailRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/CodeDetailRepositoryImpl.java
Labels: BE, 인력풀, fix

#132 백엔드 구조에 맞춰서 filter 목록 가져오는 부분에 path variable을 추가한다
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/repository/filterRepository.ts
Labels: FE, fix, done

#133 라벨과 값이 입력되지 않은 경우 에러를 보여줍니다
  FE/components/organisms/UserDetail/MyDetail/Modal/AwardModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
Labels: FE, fix

#135 채팅방 만들기 로직을 추가한다
  FE/components/molecules/UserSelectChatAutoComplete/UserSelectChatAutoComplete.tsx
  FE/components/molecules/UserSelectChatAutoComplete/index.ts
  FE/components/molecules/index.ts
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/Modal/ModalWrapper/ModalWrapper.tsx
  FE/repository/chatRepository.ts
Labels: FE, 커뮤니케이션, feature

#137 fix: 캠 끄면 불빛 없어짐
  FE/components/organisms/Layout/Layout.tsx
  FE/components/webrtc/VideoChat.tsx
  FE/components/webrtc/VideoRoomConfigModal.tsx
Labels: FE, 커뮤니케이션, fix, wip

#138 feat: 팀원 추가, 팀원 탈퇴, 팀장 변경, 팀 구성 확정 기능 추가
  BE/teamgu/build.gradle
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TeamMemberReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamListResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, feature, fix, env

#140 fix: update user detail info
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
Labels: BE, 로그인, 인력풀, 유저 편의 기능, fix

#145 fix: 이미 팀 구성중인 인원 팀 등록 불가하게 처리
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, fix

#142 인력풀에서 마이페이지로 연결한다
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
Labels: FE, 인력풀, feature, done

#143 채팅 input에 글자수 제한및 현황을 추가한다
  FE/components/molecules/ChatInput/ChatInput.tsx
Labels: FE, 커뮤니케이션, feature, done

#147 fix: TeamFilterReqDto, TrackReqDto 추가
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TeamFilterReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TrackReqDto.java
Labels: BE, 팀관리, fix

#146 전공/비전공 라디오 버튼 전체 항목 추가 및 프로퍼티 삭제한다
  FE/components/molecules/Filter/Filter.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
Labels: FE, 인력풀, feature, done

#148 feat: 채팅방 생성 직후, 채팅방 이름을 포함한 정보를 반환한다
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRoomRepositorySupport.java
Labels: DevOps, BE

#144 방 만들 때 있든 없든 해당 방으로 보내버린다
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
Labels: FE, 커뮤니케이션, feature

#151 textarea하단에 선택적으로 현재길이/최대길이를 보여줍니다
  FE/components/atoms/Textarea/Textarea.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/AwardModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
Labels: FE, 공통 컴포넌트, feature

#152 포지션 체크박스로 처리 + 5개 이상은 멀티셀렉트로 변경되도록 한다
  FE/components/molecules/Filter/Filter.tsx
  FE/components/organisms/LookupLayout/LookupLayout.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
Labels: FE, 인력풀, feature, done

#154 fix:Team Req Dto 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TrackReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/SkillResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamListResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, feature, fix

#156 fix : 유저풀에서 본인 제외 검색되게 처리
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, fix

#153 팀페이지 생성, 수정, 삭제 관련 UI 구현
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/SkillSelectAutoComplete/SkillSelectAutoComplete.tsx
  FE/components/organisms/LookupLayout/LookupLayout.tsx
  FE/components/organisms/Modal/ModalWrapper/ModalWrapper.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/repository/baseRepository.ts
  FE/repository/teamRepository.ts
  FE/utils/type.ts
Labels: FE, 팀관리, fix

#157 feat: 팀 구성 가능 여부 조회 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TeamIsCreateReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, feature, fix

#158 디테일페이지의 잡다한 수정과 공통컴포넌트의 모달을 활용합니다.
  FE/components/atoms/Textarea/Textarea.tsx
  FE/components/organisms/Modal/Modal.tsx
  FE/components/organisms/OtherUserDetail/OtherUserDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/AwardModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/pages/_app.tsx
  FE/store/modalSlice.ts
  FE/utils/constants.ts
  FE/utils/type.ts
Labels: FE, fix

#155 채팅방 다른 채팅방에 접속시 이전 메시지가 표시되는 이슈를 해결한다
  FE/components/organisms/ChatRoom/ChatRoom.tsx
Labels: FE, 커뮤니케이션, fix, done

#162 RTC 1:1 화상 통화 링크보내는 로직 연결
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/hooks/useSockStomp.ts
Labels: FE, 인력풀, 커뮤니케이션, feature, done

#163 채팅관련 버그들을 수정한다
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatInput/ChatInput.tsx
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/styles/styled.d.ts
  FE/styles/theme.ts
Labels: FE, 커뮤니케이션, feature, done

#167 feat : 파일 다운로드 엔드 포인트 생성
  BE/teamgu/src/main/java/com/teamgu/api/controller/FileDownladController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/StaticFileController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/NoticeService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/NoticeServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/NoticeFileRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/NoticeFileRepositoryImpl.java
  BE/teamgu/src/main/java/com/teamgu/handler/NoticeFileHandler.java
  BE/teamgu/src/main/java/com/teamgu/mapper/NoticeFileMapper.java
Labels: BE, feature

#165 fix: 팀 구성 가능여부 Response Model 변경, User Track 수정 로직 변경
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamIsCreateResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, 팀관리, 유저 편의 기능, fix

#164 인력풀 카드뷰 통화버튼 클릭시 uuid 에서 상대 유저id로 변경한다
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatBubbleSelect/ChatBubbleSelect.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/hooks/useSockStomp.ts
  FE/types/chat-type.d.ts
Labels: FE, 인력풀, fix, done

#166 이미지에 대한 프리뷰와 크롭을 가능하게 합니다
  FE/components/atoms/Input/Input.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/SetImageModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/package.json
  FE/utils/cropImage.ts
  FE/utils/dataURLtoFile.ts
  FE/yarn.lock
Labels: FE, feature

#168 팀원 추가 및 탈퇴
  FE/components/molecules/Checkbox/Checkbox.tsx
  FE/components/molecules/Filter/Filter.tsx
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/repository/teamRepository.ts
Labels: FE, 팀관리, feature

#169 feat: Add Team filter / search
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TeamAutoCorrectReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TeamFilterReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamAutoCorrectResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Team.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, 팀관리, 유저 편의 기능, feature, fix

#174 feat: add team leader check
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, feature

#173 feat: 사용자가 채팅방의 메세지를 어디까지 읽었는지 알 수 있다
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/StompChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserRoomOutCheckReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatMessageResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatRoomResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatTotalUnreadResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: BE, 커뮤니케이션

#175 Long으로 선언하여 에러가 발생했기 때문에 BigInteger로 변경한다
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: bug, BE, fix

#176 채팅방 조회 로직 추가, 채팅방 인원 초대 시 채팅방 명 자동 변경
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: BE

#172 팀 리더여야 팀 초대가 가능하게 수정
  FE/components/organisms/TeamManageModal/TeamManageModal.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
Labels: FE, 팀관리, fix

#178 채팅 스타일 개선 및 프로퍼티 규격을 서버와 맞추는 작업을 한다
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatBubbleSelect/ChatBubbleSelect.tsx
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/styles/theme.ts
Labels: FE, 커뮤니케이션, fix, done

#181 fix: team filter modification
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, fix

#182 feat: 채팅방 정렬 시 unRead 메세지를 상단으로 올린다
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
Labels: BE, 커뮤니케이션

#171 바뀐 데이터 형식에 맞추어 디테일 페이지를 수정합니다
  FE/components/atoms/Textarea/Textarea.tsx
  FE/components/organisms/OtherUserDetail/OtherUserDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/AwardModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ProjectModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
Labels: bug, FE

#170 관리자 프로젝트 관리
  FE/components/molecules/ProjectCard/ProjectCard.tsx
  FE/components/molecules/SimpleSelect/SimpleSelect.tsx
  FE/components/molecules/index.ts
  FE/components/organisms/AdminLayout/AdminLayout.stories.tsx
  FE/components/organisms/AdminLayout/AdminLayout.tsx
  FE/components/organisms/AdminLayout/index.ts
  FE/components/organisms/AdminMenuSidebarLeft/AdminMenuSidebarLeft.stories.tsx
  FE/components/organisms/AdminMenuSidebarLeft/AdminMenuSidebarLeft.tsx
  FE/components/organisms/AdminProjectManage/AdminProjectManage.stories.tsx
  FE/components/organisms/AdminProjectManage/AdminProjectManage.tsx
  FE/components/organisms/AdminProjectManage/index.ts
  FE/components/organisms/AdminProjectManageModal/AdminProjectManageModal.stories.tsx
  FE/components/organisms/AdminProjectManageModal/AdminProjectManageModal.tsx
  FE/components/organisms/AdminProjectManageModal/index.ts
  FE/components/organisms/index.ts
  FE/pages/admin/index.tsx
  FE/utils/constants.ts
  FE/utils/dummy.ts
Labels: FE, 관리자 편의 기능, feature

#179 채팅 방 나가는 요청 엔드포인트 함수를 제작 및 로직에 연결한다
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/repository/chatRepository.ts
Labels: FE, 커뮤니케이션, feature, done

#180 next/babel 문제로 린팅 안되는 문제를 위해 prettier 포메팅 한다
  .vscode/settings.json
  FE/.vscode/settings.json
Labels: FE, fix, env, done

#183 fix : 유저풀 입력값 확인
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: bug, BE, 인력풀, fix

#184 fix: team controller sysout 제거, team filter 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/TeamController.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, fix

#186 fix: team filter modification
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, fix

#188 관리자 대시보드 레이아웃 및 도표
  FE/components/molecules/BigDonutChart/BigDonutChart.stories.tsx
  FE/components/molecules/BigDonutChart/BigDonutChart.tsx
  FE/components/molecules/BigDonutChart/index.ts
  FE/components/molecules/DonutChart/DonutChart.stories.tsx
  FE/components/molecules/DonutChart/DonutChart.tsx
  FE/components/molecules/DonutChart/index.ts
  FE/components/molecules/index.ts
  FE/components/organisms/AdminDashboard/AdminDashboard.stories.tsx
  FE/components/organisms/AdminDashboard/AdminDashboard.tsx
  FE/components/organisms/AdminDashboard/index.ts
  FE/components/organisms/AdminLayout/AdminLayout.tsx
  FE/components/organisms/index.ts
  FE/package.json
  FE/utils/dummy.ts
  FE/yarn.lock
Labels: FE, 관리자 편의 기능, feature

#187 팀 페이지 필터링 버그 수정
  FE/components/molecules/UserSelectTeamAutoComplete/UserSelectTeamAutoComplete.stories.tsx
  FE/components/molecules/UserSelectTeamAutoComplete/UserSelectTeamAutoComplete.tsx
  FE/components/molecules/UserSelectTeamAutoComplete/index.ts
  FE/components/molecules/index.ts
  FE/components/organisms/TeamManageModal/TeamManageModal.stories.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.stories.tsx
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/repository/baseRepository.ts
  FE/repository/teamRepository.ts
  FE/utils/type.ts
Labels: FE, 팀관리, fix

#185 메인페이지를 완성합니다
  FE/components/organisms/LoginComponent/LoginComponent.stories.tsx
  FE/components/organisms/LoginComponent/LoginComponent.tsx
  FE/components/organisms/LoginComponent/index.ts
  FE/components/organisms/Main/Main.stories.tsx
  FE/components/organisms/Main/Main.tsx
  FE/components/organisms/Main/index.ts
  FE/components/organisms/Navbar/Navbar.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/SetImageModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/components/organisms/index.ts
  FE/pages/_app.tsx
  FE/pages/index.tsx
  FE/pages/login/index.tsx
  FE/public/mainPage_background.png
  FE/public/star1.png
  FE/public/star2.png
  FE/public/star3.png
  FE/public/star4.png
  FE/public/star5.png
  FE/public/star6.png
  FE/public/star7.png
  FE/public/star8.png
  FE/public/teamgu_logo.png
Labels: FE, done

#191 feat : 유저 프로필 이미지 등록 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/UserProfileImgDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInfoReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/handler/NoticeFileHandler.java
  BE/teamgu/src/main/java/com/teamgu/handler/ProfileImageHandler.java
Labels: BE, feature, 유저 정보 수정

#193 fix : UserController 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
Labels: BE, fix, 유저 정보 수정

#194 채팅의 핵심 기능을 추가한다
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatInviteNUsersReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatRoomLeaveReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatRoomModifyReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatRoomRegistReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRoomRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: BE, 커뮤니케이션

#189 방 만들기, 팀 초대, rtc Call, 전체노티 등에 대해 변형될 엔드포인트 형태에 맞게끔 리팩토링 한다
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatInput/ChatInput.tsx
  FE/components/molecules/Filter/Filter.stories.tsx
  FE/components/molecules/Filter/Filter.tsx
  FE/components/molecules/FloatingButton/FloatingButton.tsx
  FE/components/molecules/Notification/Notification.stories.tsx
  FE/components/molecules/Notification/Notification.tsx
  FE/components/molecules/Notification/index.ts
  FE/components/molecules/ProfileContainer/ProfileContainer.tsx
  FE/components/molecules/UserSelectChatAutoComplete/UserSelectChatAutoComplete.tsx
  FE/components/molecules/index.ts
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/Modal/HocModal/HocModal.tsx
  FE/components/organisms/Modal/HocModal/index.ts
  FE/components/organisms/Modal/Modal.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/hooks/useSockStomp.ts
  FE/pages/_app.tsx
  FE/repository/chatRepository.ts
  FE/store/modalSlice.ts
  FE/utils/constants.ts
Labels: FE, 커뮤니케이션, feature, done

#196 팀 초대 기능을 구현한다
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/StompChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserInviteTeamReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ChatMessageResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/Chat.java
  BE/teamgu/src/main/java/com/teamgu/mapper/ChatMapper.java
Labels: BE, 팀관리, 커뮤니케이션

#197 fix : 파일 컨트롤러, 유저 관련 endpoint 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/StaticFileController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
Labels: BE, fix, 유저 정보 수정

#198 fix : FileController에서 JWT 토큰 인증 제외
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
Labels: BE, fix, 유저 정보 수정

#199 Nullable 옵션을 수정한다
  BE/teamgu/src/main/java/com/teamgu/database/entity/Chat.java
Labels: bug, BE, fix

#200 네브바의 디자인을 수정합니다.
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/Navbar/Navbar.tsx
Labels: FE

#201 fix : ProjectDetail Entity 수정
  BE/teamgu/src/main/java/com/teamgu/database/entity/ProjectDetail.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/pk/ProjectDetailPK.java
Labels: BE, 인력풀, fix

#202 fix : 반환 데이터형 확인하기 위한 log 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
Labels: BE, fix, 유저 정보 수정

#203 feat: Select Box select, insert, delete
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ProjectCodeReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/CodeResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/ProjectInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature

#204 feat: project 추가 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature

#206 Feature/user profile
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoResDto.java
Labels: BE, fix, 유저 정보 수정

#205 feat: add project, update project, delete project
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ProjectDetailRepository.java
Labels: BE, 관리자 편의 기능, feature

#208 fix : 유저 프로필 등록 잔 오류 처리
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/handler/NoticeFileHandler.java
  BE/teamgu/src/main/java/com/teamgu/handler/ProfileImageHandler.java
Labels: BE, fix, 유저 정보 수정

#209 fix : UserPool 오류 문구 수정
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, fix

#210 feat : FE 유저 상태 초기화시 필요한 엔드 포인트 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/LoginReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/LoginResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
Labels: BE, 로그인, feature

#207 관리자 프로젝트 추가, 수정, 삭제
  FE/components/molecules/ProjectCard/ProjectCard.stories.tsx
  FE/components/molecules/ProjectCard/ProjectCard.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/organisms/AdminDashboard/AdminDashboard.tsx
  FE/components/organisms/AdminLayout/AdminLayout.tsx
  FE/components/organisms/AdminProjectManage/AdminProjectManage.tsx
  FE/components/organisms/AdminProjectManageModal/AdminProjectManageModal.stories.tsx
  FE/components/organisms/AdminProjectManageModal/AdminProjectManageModal.tsx
  FE/repository/adminRepository.ts
  FE/styles/styled.d.ts
  FE/styles/theme.ts
  FE/utils/constants.ts
  FE/utils/dummy.ts
  FE/utils/type.ts
Labels: FE, 관리자 편의 기능, feature

#212 채팅 관련 버그 해결 및 제목 수정, 방 나가기 등의 로직을 추가한다
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/DropdownMenu/DropdownMenu.stories.tsx
  FE/components/molecules/DropdownMenu/DropdownMenu.tsx
  FE/components/molecules/DropdownMenu/index.ts
  FE/components/molecules/Tooltip/Tooltip.tsx
  FE/components/molecules/Tooltip/index.ts
  FE/components/molecules/index.ts
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/hooks/useSockStomp.ts
  FE/repository/chatRepository.ts
Labels: FE, 커뮤니케이션, feature, done

#213 프로필 이미지 업로드 작업을 완성합니다
  FE/components/organisms/Navbar/Navbar.tsx
  FE/components/organisms/OtherUserDetail/OtherUserDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/SetImageModal.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetail.tsx
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/next.config.js
  FE/repository/userprofile.ts
  FE/store/authSlice.ts
  FE/utils/constants.ts
  FE/utils/dataURLtoFile.ts
Labels: FE, feature

#214 feat: DashBoard by region, track
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardDetailInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature

#216 feat : 인력풀 유저 검색 자동완성 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserPoolController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolNameReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolNameResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, feature

#217 채팅방의 기능 수정 및 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/ChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/StompChatController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/ChatRoomModifyReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/ChatServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/UserChatRoom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/ChatRoomRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserChatRoomRepositorySupport.java
Labels: BE, 커뮤니케이션

#218 관리자 대시보드 테이블
  FE/components/molecules/BigDonutChart/BigDonutChart.tsx
  FE/components/molecules/DashboardTable/DashboardTable.stories.tsx
  FE/components/molecules/DashboardTable/DashboardTable.tsx
  FE/components/molecules/DashboardTable/index.ts
  FE/components/molecules/DonutChart/DonutChart.tsx
  FE/components/molecules/index.ts
  FE/components/organisms/AdminDashboard/AdminDashboard.tsx
  FE/components/organisms/AdminLayout/AdminLayout.tsx
  FE/components/organisms/AdminMenuSidebarLeft/AdminMenuSidebarLeft.tsx
  FE/components/organisms/Layout/Layout.tsx
  FE/package.json
  FE/repository/adminRepository.ts
  FE/utils/constants.ts
  FE/utils/dummy.ts
  FE/yarn.lock
Labels: FE, 관리자 편의 기능, feature

#219 네브바 오류 수정
  FE/components/organisms/Navbar/Navbar.tsx
Labels: FE, fix

#223 fix : Data 어노테이션 제거
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/LoginResDto.java
Labels: BE, 로그인, fix

#222 feat : 인력풀 페이지네이션 기능 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserPoolController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolPageReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolNameResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolPageResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, feature

#225 fix : 로그인시 반환되는 프로필 url 변경
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
Labels: BE, 로그인, fix

#227 fix : 유저풀에서 반환하는 유저 프로필 url 변경
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserPoolResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
Labels: BE, 인력풀, fix

#228 fix : 더미데이터 추가시에 default 이미지 정보 들어가게 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
Labels: BE, fix

#221 바 차트(Bar Chart) 컴포넌트
  FE/components/molecules/DashboardBarChart/DashboardBarChart.stories.tsx
  FE/components/molecules/DashboardBarChart/DashboardBarChart.tsx
  FE/components/molecules/DashboardBarChart/index.ts
  FE/components/molecules/DashboardTable/DashboardTable.tsx
  FE/components/molecules/index.ts
  FE/components/organisms/AdminDashboard/AdminDashboard.tsx
  FE/components/organisms/AdminLayout/AdminLayout.tsx
  FE/components/organisms/AdminProjectManage/AdminProjectManage.tsx
Labels: FE, 관리자 편의 기능, fix

#224 feat: Dash Board Table 데이터 조회 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardDetailInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardDetailResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/DashBoardTableResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature, fix

#215 규격에 맞춰서 메시지 처리 라우팅
  FE/components/molecules/ChatBubble/ChatBubble.tsx
  FE/components/molecules/ChatBubbleSelect/ChatBubbleSelect.tsx
  FE/components/molecules/DropdownMenu/DropdownMenu.tsx
  FE/components/organisms/ChatList/ChatList.tsx
  FE/components/organisms/ChatRoom/ChatRoom.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/hooks/useSockStomp.ts
  FE/repository/chatRepository.ts
  FE/types/chat-type.d.ts
Labels: FE, 커뮤니케이션, feature

#231 feat : 비밀번호 수정시 원본 비밀번호와 대조한다
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/PasswordReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
Labels: BE, fix, 유저 정보 수정

#220 3가지의 기능을 가진 ProtectedRoute를 정의합니다
  FE/components/organisms/Layout/Layout.tsx
  FE/components/organisms/Navbar/Navbar.tsx
  FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
  FE/components/organisms/ProtectedRoute/index.ts
  FE/components/organisms/index.ts
  FE/pages/_app.tsx
  FE/repository/userprofile.ts
Labels: FE, 유저 편의 기능, feature

#229 공통컴포넌트를 활용하여 네브바를 리팩토링합니다
  FE/components/molecules/DropdownMenu/DropdownMenu.tsx
  FE/components/organisms/Navbar/Navbar.tsx
Labels: FE, fix

#232 수정된 이미지 url을 반영합니다
  FE/store/authSlice.ts
  FE/utils/constants.ts
Labels: FE, fix

#234 인력풀에 페이지네이션을 적용한다
  FE/components/molecules/Pagination/Pagination.tsx
  FE/components/molecules/Pagination/index.ts
  FE/components/molecules/index.ts
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/package.json
  FE/yarn.lock
Labels: FE, 인력풀, feature, done

#233 관리자 대시보드 하단 테이블 백엔드 연동
  FE/components/organisms/AdminDashboard/AdminDashboard.tsx
  FE/repository/adminRepository.ts
  FE/utils/constants.ts
  FE/utils/dummy.ts
Labels: FE, 관리자 편의 기능

#239 feat: 팀구성 현황 조회 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/AdminTeamManagementReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/AdminTeamManagementHumanResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/AdminTeamManagementResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature

#238 fix : 용재님 요청사항 처리
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserPoolController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolPageReqDto.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, fix

#242 팀페이지 이미지 경로 백엔드 구현 전까지 주석처리
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
Labels: FE, 팀관리, hotfix

#243 fix : 인력풀 자동완성에 조건 추가
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserPoolController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/UserPoolNameReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserPoolServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryCustom.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserPoolRepositoryImpl.java
Labels: BE, 인력풀, fix

#235 비밀번호 변경 모달 생성
  FE/components/atoms/Input/Input.tsx
  FE/components/organisms/Modal/Modal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/ChangePasswordModal.tsx
  FE/components/organisms/UserDetail/MyDetail/Modal/index.ts
  FE/components/organisms/UserDetail/MyDetail/MyDetailEdit.tsx
  FE/repository/userprofile.ts
  FE/store/modalSlice.ts
  FE/utils/constants.ts
Labels: FE, feature, 유저 정보 수정

#241 관리자 팀 목록 조회
  FE/components/molecules/DashboardTable/DashboardTable.tsx
  FE/components/molecules/DashboardTable/index.ts
  FE/components/molecules/ReactTable/ReactTable.stories.tsx
  FE/components/molecules/ReactTable/ReactTable.tsx
  FE/components/molecules/ReactTable/index.ts
  FE/components/molecules/index.ts
  FE/components/organisms/AdminDashboard/AdminDashboard.tsx
  FE/components/organisms/AdminLayout/AdminLayout.tsx
  FE/components/organisms/AdminMenuSidebarLeft/AdminMenuSidebarLeft.tsx
  FE/components/organisms/AdminTeamManage/AdminTeamManage.tsx
  FE/components/organisms/AdminTeamManage/index.ts
  FE/components/organisms/AdminUserManage/AdminUserManage.tsx
  FE/components/organisms/AdminUserTable/index.ts
  FE/components/organisms/index.ts
  FE/repository/adminRepository.ts
  FE/utils/constants.ts
Labels: FE, 팀관리, feature

#240 관리자가 엑셀을 통한 유저 Import 및 등록, 유저 Export가 가능하다
  BE/teamgu/build.gradle
  BE/teamgu/src/main/java/com/teamgu/api/controller/ExcelController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/UserRegistDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/TeamWithUserToExcelReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/HorizontalByTeamResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/UserInfoByTeam.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/VerticalByUserResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/TeamServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 관리자 편의 기능

#244 fix : 팀 구성원 프로필 이미지 url 수정
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/TeamMemberInfoResDto.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 팀관리, fix

#237 인력풀 검색에 자동완성 로직을 연결한다
  FE/components/molecules/Filter/Filter.tsx
  FE/components/molecules/UserSelectAutoComplete/UserSelectAutoComplete.tsx
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/Modal/AlertModal/AlertModal.tsx
  FE/components/organisms/UserStatus/UserStatus.tsx
  FE/components/organisms/UserStatusCard/UserStatusCard.tsx
  FE/repository/filterRepository.ts
  FE/store/authSlice.ts
  FE/utils/constants.ts
Labels: FE, 인력풀, feature, done

#245 관리자 회원 정보 추가/수정 모달
  FE/components/molecules/DashboardBarChart/DashboardBarChart.stories.tsx
  FE/components/organisms/AdminTeamManage/AdminTeamManage.tsx
  FE/components/organisms/AdminUserManage/AdminUserManage.tsx
  FE/components/organisms/AdminUserManageModal/AdminUserManageModal.stories.tsx
  FE/components/organisms/AdminUserManageModal/AdminUserManageModal.tsx
  FE/components/organisms/AdminUserManageModal/index.ts
  FE/components/organisms/TeamStatusCard/TeamStatusCard.tsx
  FE/components/organisms/index.ts
Labels: FE, 관리자 편의 기능, feature

#249 팀 페이지에서 내 팀을 맨 위로
  FE/components/organisms/TeamStatus/TeamStatus.tsx
Labels: FE, 팀관리, fix

#247 자잘한 오류들을 수정한다
  FE/components/organisms/ChatRoute/ChatRoute.tsx
  FE/components/organisms/Navbar/Navbar.tsx
  FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
  FE/components/organisms/TeamStatus/TeamStatus.tsx
  FE/repository/userprofile.ts
  FE/store/authSlice.ts
Labels: FE, fix, done

#246 feat: 관리자의 교육생 관리 조회, 반 Select Box 조회
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/AdminManagementReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/res/AdminUserManagementResDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature

#248 feat : 비밀번호 초기화 기능 추가
  BE/teamgu/build.gradle
  BE/teamgu/src/main/java/com/teamgu/api/controller/JwtAuthController.java
  BE/teamgu/src/main/java/com/teamgu/api/controller/UserController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/MailDto.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/PasswordInitReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/MailService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/MailServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/UserServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/common/util/RandomPwdUtil.java
  BE/teamgu/src/main/java/com/teamgu/config/SecurityConfig.java
  BE/teamgu/src/main/java/com/teamgu/database/entity/User.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/UserRepositorySupport.java
Labels: BE, feature, 유저 정보 수정

#250 feat: Student Class 추가 및 삭제, Admin Team Management Error 수정
  BE/teamgu/src/main/java/com/teamgu/api/controller/AdminController.java
  BE/teamgu/src/main/java/com/teamgu/api/dto/req/StdClassReqDto.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminService.java
  BE/teamgu/src/main/java/com/teamgu/api/service/AdminServiceImpl.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/AdminRepositorySupport.java
  BE/teamgu/src/main/java/com/teamgu/database/repository/TeamRepositorySupport.java
Labels: BE, 관리자 편의 기능, feature, fix

#251 fix : MailService 에러 수정
  BE/teamgu/src/main/java/com/teamgu/api/service/MailServiceImpl.java
Labels: bug, BE, fix, 유저 정보 수정

#252 fix : application.yml 재수정
  BE/teamgu/src/main/resources/application.yml
Labels: bug, BE, fix, 유저 정보 수정
